name: Build paper

on:
  push:
    tags: ['*']  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整的Git历史，Paper构建需要

      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Set up JDK 21
        uses: actions/setup-java@v4  # 更新到最新版本
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Build with Gradle
        run: |
          chmod +x gradlew 
          ./gradlew clean 
          ./gradlew applyPatches
          ./gradlew createMojmapPaperclipJar

      - name: Prepare JAR
        id: prepare_jar
        run: |
          JAR_PATH=$(find paper-server/build/libs -name "*.jar" ! -name "*sources*" ! -name "*javadoc*" | head -n 1)
          if [ -z "$JAR_PATH" ]; then
            echo "No JAR file found!"
            exit 1
          fi
          cp "$JAR_PATH" ./paper.jar
          echo "JAR_SIZE=$(ls -lh ./paper.jar | awk '{print $5}')" >> $GITHUB_OUTPUT
          echo "JAR_NAME=$(basename "$JAR_PATH")" >> $GITHUB_OUTPUT

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper-artifact
          path: paper.jar
          retention-days: 30

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: paper-artifact

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: paper.jar
          tag_name: ${{ github.ref_name }}
          name: "Paper ${{ github.ref_name }}"
          body: |
            ## Paper Server Build ${{ github.ref_name }}
            
            This release contains the Paper server JAR file built from the latest source code.
            
            ### Installation
            1. Download the `paper.jar` file
            2. Place it in your server directory
            3. Run with: `java -Xmx2G -Xms2G -jar paper.jar nogui`
            
            ### Requirements
            - Java 21 or higher
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
