name: Build paper

on:
  push:
    tags: ['*']  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Gradle
        run: chmod +x gradlew && ./gradlew clean applyPatches createMojmapPaperclipJar

      - name: Prepare JAR
        id: prepare_jar
        run: |
          JAR_PATH=$(find paper-server/build/libs -name "*.jar" ! -name "*sources*" ! -name "*javadoc*" | head -n 1)
          cp "$JAR_PATH" ./paper.jar
          echo "JAR_SIZE=$(ls -lh ./velocity.jar | awk '{print $5}')" >> $GITHUB_OUTPUT

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper-artifact
          path: paper.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: paper-artifact

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: paper.jar
          tag_name: ${{ github.ref_name }}
          name: "Velocity ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
